dist: bionic

matrix:
  include:
    - language: python
      python: 
        - 3.7
      install: 
        - pip install pytest
      script:
        - python3 -m pytest

    - language: node_js
      node_js:
        - 12.13
      install:
        - yarn install
      script:
        - yarn test
